// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import { Layout } from "@/components";

export const metadata = {
  title: "Shopz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body>{children}</body>
    // </html>
    <Layout>
      <body>{children}</body>
    </Layout>
  );
}
