// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import { Layout } from "@/components";
import { ContextWrapper } from "@/context";

export const metadata = {
  title: "Shopz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextWrapper>
          {children}
        </ContextWrapper>
      </body>
    </html>
    // <Layout>
    //   <body>{children}</body>
    // </Layout>
  );
}
